FROM node:18-alpine
WORKDIR /usr/src/app
RUN apk add --no-cache python3 make g++
COPY package.json package-lock.json turbo.json ./
RUN npm install -g esbuild
COPY apps ./apps
COPY packages ./packages
RUN npm install
RUN cd packages/db && npx prisma generate && cd ../..
RUN npm run build
CMD ["npm", "run", "start:api-server"]