name: Build and Deploy
on:
  push:
    paths:
      - "apps/api-server/**"
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.api-server
        push: true
        tags: pradeepkundekar0101/unite-api:${{ github.sha }}

    - name: Update Kubernetes manifests
      run: |
        echo "Cloning infrastructure repository..."
        git clone https://x-access-token:${INFRA_REPO_TOKEN}@github.com/pradeepkundekar0101/meta-ops.git
        cd unite-ops
        
        echo "Updating image tag..."
        cd api-server
        sed -i "s|image: pradeepkundekar0101/unite-api:.*|image: pradeepkundekar0101/unite-api:${GITHUB_SHA}|" deployment.yaml
        
        echo "Committing and pushing changes..."
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Update unite-api image to ${GITHUB_SHA}"
        git push
      env:
        INFRA_REPO_TOKEN: ${{ secrets.INFRA_REPO_TOKEN }}